### PR TITLE
175514735 older eruptions

### PR DESCRIPTION
**Pull request by dstrawberrygirl**
Using the database of volcanoes and eruptions, now pulling down individual eruptions for the past 40 years (adjustable via the start time) to display on the map and show over time as we do with earthquakes.

The fact that an eruption is not an instantaneous event makes for slightly different logic, since some volcanoes have been actively erupting for approx. 100 years. 

There have been 11k recorded eruptions, which would be too many to display all at once with the historical data on top of the earthquakes. Perhaps if there was a simple metric to filter the eruptions this might be possible, but for now I have bundled them back up so they behave more like the old volcanoes, but with additional information on the years they erupted.

### CODE REVIEW

**Review by pjanik — COMMENTED** [review]
I'm still seeing some issues when I play with http://seismic-explorer.concord.org/branch/older-eruptions/index.html, but I guess it'll be easier to discuss that on Slack / Zoom when you're back.

**Comment by dstrawberrygirl** [comment]
@pjanik I believe I fixed the eruption colors in [53562dd](https://github.com/concord-consortium/seismic-explorer/pull/35/commits/53562dd5385b4322a8e32d526701bf04fa6d35d5) by updating the sprite color attributes each render tick for eruptions. It doesn't seem to have hit performance, and the test I've been using (Iceland / Hekla eruption from Jan 16 to March 10 1991) seems to respond correctly to the time slider now. Once the PR finally deploys this will be testable [here](https://seismic-explorer.concord.org/branch/older-eruptions/index.html?centerLat=65&centerLng=-18&centeredInitialZoom=6&sizeToFitBounds=false&earthquakesVisible=false&eruptionsVisible)

**Comment by pjanik** [comment]
I'm going to look now if I can find some without exposing time as a global variable in `window`.

**Review by pjanik — APPROVED** [review]
OK, I've pushed a change that refactors eruptions color rendering, so we don't expose and use `window.` variables.

I think it's kinda closer to your initial approach if I remember correctly. I'm setting `active` in `getVisibleEruptions`. 

I also moved color update to _processNewData, as it makes a bit more sense. `update` function was meant mostly for visual transitions, without expecting that new data might be set there. It should limit the number of writes to the color attr array.

I was playing with Iceland cases that we looked at yesterday and things seem to behave okay.

**Comment by dstrawberrygirl** [comment]
This is great, @pjanik, thanks! I guess the color attr array update was the missing piece, and the data property in getVisibleEruptions was sufficient after all. Thanks for the update to this, I'll get this merged and finished up.

**Pull request merged**
